apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-set
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/khaoulahamza/gitops-environments
        revision: main
        directories:
          - path: argocd-applications
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/khaoulahamza/gitops-environments
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: default
