name: malek-roukaya-internapp-front
namespace: production-malek-roukaya-internapp
replicaCount: 2
image:
  repository: "windazureacrch0s.azurecr.io/malek-roukaya-internapp-front"
  tag: "7b997574a8c18e967ba45737b3b174220554e4dc"
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: azureacr-secret
service:
  type: ClusterIP
  port: 80
  targetPort: 80
ingress:
  enabled: true
  className: nginx
  # Réutilisation du DNS existant (aucune modification Azure requise)
  host: devops-dashboard-prod.swedencentral.cloudapp.azure.com
  # Chemin dédié pour isoler cette application
  path: /internapp
  pathType: Prefix
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    # Indispensable : retire "/internapp" de l'URL avant de l'envoyer au pod
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    # Gestion des chemins avec capture group pour la réécriture
    nginx.ingress.kubernetes.io/use-regex: "true"
  tls:
    - hosts:
        - devops-dashboard-prod.swedencentral.cloudapp.azure.com
      # Nom de secret unique pour éviter tout conflit avec le dashboard
      secretName: internapp-front-tls
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
env: []
database:
  enabled: false
