name: malek-roukaya-internapp-back
namespace: production-malek-roukaya-internapp
replicaCount: 2
image:
  repository: "windazureacrch0s.azurecr.io/malek-roukaya-internapp-back"
  tag: "7b997574a8c18e967ba45737b3b174220554e4dc"
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: azureacr-secret
service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
ingress:
  enabled: true
  className: nginx
  # Même hôte que le frontend pour éviter les problèmes CORS et utiliser l'IP existante
  host: devops-dashboard-prod.swedencentral.cloudapp.azure.com
  # Chemin dédié pour le backend. Le regex permet de capturer ce qui suit "/api"
  path: /internapp/api(/|$)(.*)
  pathType: ImplementationSpecific
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    # Réécrit l'URL pour que le conteneur reçoive la requête à la racine "/"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
  tls:
    - hosts:
        - devops-dashboard-prod.swedencentral.cloudapp.azure.com
      # Nom de secret unique pour le backend
      secretName: internapp-back-tls
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
env: []
database:
  enabled: true
  type: "postgresql"
  name: "malek_roukaya_internapp_db"
  namespace: "production-malek-roukaya-internapp"
  storage: 1Gi
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  # Désactivation de la HA pour garantir un déploiement stable et léger
  ha:
    enabled: false
