name: malek-roukaya-internapp-back
replicaCount: 1
image:
  repository: "192.168.1.239:8085/selfkhaoula/malek-roukaya-internapp-back"
  tag: "81c3d3927cf1ca1dcb46d73e3cc49682a2a19a3a"
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: nexus-registry-secret
service:
  type: ClusterIP
  port: 80
  targetPort: 80
ingress:
  enabled: true
  className: nginx
  host: malek-roukaya-internapp-back.staging.local
  path: /
  pathType: Prefix
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
env: []
