name: malek-roukaya-internapp-back
replicaCount: 1
image:
  repository: "192.168.1.239:8085/selfkhaoula/malek-roukaya-internapp-back"
  tag: "a3ac76e2eebb22d13fa9cbc08b0cd803e28aa2ff"
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: nexus-registry-secret
service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30080
ingress:
  enabled: false
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
env: []
database:
  enabled: true
  type: "postgresql"
  name: "malek_roukaya_internapp_back_db"
  storage: 1Gi
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
