# environments/staging/malek-roukaya-internapp-back/values.yaml
name: malek-roukaya-internapp-back
replicaCount: 1
image:
  repository: "192.168.1.239:8085/selfkhaoula/malek-roukaya-internapp-back"
  tag: "a4edc38df01ce373a6d837f4b0a1415204e73816"
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: nexus-registry-secret
service:
  type: ClusterIP
  port: 80
  targetPort: 80
ingress:
  enabled: true
  className: nginx
  host: malek-roukaya-internapp-back.staging.local
  path: /
  pathType: Prefix
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

env: []

database:
  enabled: true
  type: "postgresql"
  name: "malek_roukaya_internapp_back_db"
  storage: 1Gi
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
