name: malek-roukaya-internapp-front
replicaCount: 1
image:
  repository: "192.168.1.239:8085/selfkhaoula/malek-roukaya-internapp-front"
  tag: "8ea0117dee4b0a8e6fdf8333b13f6c9d53b2480d"
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: nexus-registry-secret
service:
  type: ClusterIP
  port: 80
  targetPort: 80
ingress:
  enabled: true
  className: nginx
  host: malek-roukaya-internapp-front.staging.local
  path: /
  pathType: Prefix
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
env: []
