name: malek-roukaya-internapp-back
namespace: staging-malek-roukaya-internapp
replicaCount: 1
image:
  repository: "192.168.1.239:8085/selfkhaoula/malek-roukaya-internapp-back"
  tag: "1442657f00328e150f1e1257cfb0843b7fa2e551"
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: nexus-registry-secret
service:
  type: ClusterIP
  port: 80
  targetPort: 80
ingress:
  enabled: true
  className: nginx
  host: malek-roukaya-internapp-back.staging.local
  path: /
  pathType: Prefix
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
env: []
database:
  enabled: true
  type: "postgresql"
  name: "malek_roukaya_internapp_db"
  namespace: "staging-malek-roukaya-internapp"
  storage: 1Gi
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  ha:
    enabled: true
    replicas: 2
    proxy:
      enabled: true
      replicas: 2
