name: malek-roukaya-internapp

replicaCount: 1

image:
  repository: "192.168.1.239:8085/selfkhaoula/malek-roukaya-internapp"
  tag: "ecdff7887023e3181f15cc189137ea9d7ca02631"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: nexus-registry-secret

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true
  className: nginx
  host: malek-roukaya-internapp.local
  path: /
  pathType: Prefix

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

env: []
