apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: alloy
    targetRevision: 1.13.0
    helm:
      valuesObject:
        controller:
          type: deployment
          tolerations:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
              effect: NoSchedule
        configReloader:
          resources:
            requests:
              cpu: 1m
              memory: 16Mi
        alloy:
          resources:
            requests:
              cpu: 5m
              memory: 64Mi
          configMap:
            content: |
              discovery.kubernetes "pods" {
                role = "pod"
              }
              discovery.relabel "system" {
                targets = discovery.kubernetes.pods.targets
                rule {
                  source_labels = ["__meta_kubernetes_namespace"]
                  regex         = "kube-system|observability"
                  action        = "keep"
                }
                rule {
                  source_labels = ["__meta_kubernetes_namespace"]
                  target_label  = "namespace"
                }
                rule {
                  source_labels = ["__meta_kubernetes_pod_name"]
                  target_label  = "pod"
                }
                rule {
                  source_labels = ["__meta_kubernetes_pod_container_name"]
                  target_label  = "container"
                }
              }
              loki.source.kubernetes "system" {
                targets    = discovery.relabel.system.output
                forward_to = [loki.write.default.receiver]
              }
              loki.source.kubernetes_events "events" {
                forward_to = [loki.write.default.receiver]
              }
              loki.write "default" {
                endpoint {
                  url = "http://loki-gateway.observability.svc.cluster.local/loki/api/v1/push"
                }
              }
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true