apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: malek-roukaya-internapp
  namespace: argocd
spec:
  project: stagiaires
  source:
    repoURL: https://github.com/khaoulahamza/devops-templates
    targetRevision: main
    path: helm-charts/app-generic
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/khaoulahamza/gitops-environments/main/environments/staging/malek-roukaya-internapp/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: staging-malek-roukaya-internapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
