name: mehdi-sapp-gateway-service
namespace: staging-mehdi-sapp-gateway-service
replicaCount: 1
image:
  repository: "192.168.1.239:8085/selfkhaoula/mehdi-sapp-gateway-service"
  tag: "acec4e3321004e363210cdf83971e77b32eaec2d"
  pullPolicy: IfNotPresent
imagePullSecrets:
- name: nexus-registry-secret
service:
  type: ClusterIP
  port: 80
  targetPort: 80
ingress:
  enabled: true
  className: nginx
  host: mehdi-sapp-gateway-service.staging.local
  path: /
  pathType: Prefix
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
env: []
