name: my-angular-app

image:
  repository: 192.168.1.239:8085/selfkhaoula/app  # ← 8085 pas 8444, selfkhaoula pas docker-hub
  tag: "latest"
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: nexus-registry-secret

replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true
  className: nginx
  host: my-app.staging.local
  path: /
  pathType: Prefix

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

env: []
